version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["npm", "start"] 
